services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Los_Angeles
      - PASSWORD=${VSCODE_PASSWORD}
      - SUDO_PASSWORD=${VSCODE_SUDO_PASSWORD}
      - DEFAULT_WORKSPACE=/config/workspace
      - PROXY_DOMAIN=${VSCODE_PROXY_DOMAIN}
    volumes:
      - ${VSCODE_CONFIG_PATH}:/config
      - ${VSCODE_WORKSPACE_PATH}:/config/workspace
    labels:
      - traefik.enable=true
      - traefik.http.routers.vscode.rule=Host(`${VSCODE_PROXY_DOMAIN}`)
      - traefik.http.routers.vscode.entrypoints=https
      - traefik.http.routers.vscode.tls=true
      - traefik.http.routers.vscode.tls.certresolver=porkbun
      - traefik.http.services.vscode.loadbalancer.server.port=8443
    restart: unless-stopped
    networks:
      - traefik
networks:
  traefik:
    external: true
