# https://gethomepage.dev/configs/settings
title: Homelab
theme: dark # or light
color: slate
headerStyle: boxedWidgets
showStats: true
language: en
target: _blank # Possible options include _blank, _self, and _top
quicklaunch:
    searchDescriptions: false
    hideInternetSearch: false
    showSearchSuggestions: true
    hideVisitURL: false
    provider: custom
    url: https://kagi.com/search?q=
    target: _blank
    suggestionUrl: https://kagi.com/api/autosuggest?q=
layout:
    Media:
        style: row
        columns: 3
    Infra:
        style: row
        columns: 3
