services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: uid:gid
    network_mode: host
    volumes:
      - ${JELLYFIN_DATA_PATH}:/config
      - ${JELLYFIN_CACHE_PATH}:/cache
      - type: bind
        source: ${JELLYFIN_MEDIA_PATH}
        target: /Media
    restart: unless-stopped
networks: {}
