services:
  jellyfin:
    # uses port 8096
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: uid:gid
    network_mode: host
    volumes:
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${JELLYFIN_DATA_PATH}:/data
    restart: unless-stopped
networks: {}
