# based on https://github.com/TechHutTV/homelab/blob/be80f0899f6fa8bd7f164867e2acf9516b3103aa/media/arr-compose.yaml
#
# _CONFIG_PATHs should point to app-specific config folders
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6767:6767 # bazarr
      - 6881:6881 # deluge
      - 6881:6881/udp # deluge
      - 7878:7878 # radarr
      - 8112:8112 # deluge web interface
      - 8989:8989 # sonarr
      - 9696:9696 # prowlarr
      - 58846:58846 # deluge thin client
    volumes:
      - ${GLUETUN_CONFIG_PATH}:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES} # ex: 10.73.65.231/32
      - SERVER_COUNTRIES=Germany,Netherlands,Sweden,Switzerland,UK,USA
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-deluge/#usage
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Los_Angeles
      - DELUGE_LOGLEVEL=info
    volumes:
      - ${DELUGE_CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/data
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
  # https://docs.linuxserver.io/images/docker-sonarr/#usage
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SONARR_CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/data
    network_mode: service:gluetun
    depends_on:
      - gluetun
  # https://docs.linuxserver.io/images/docker-radarr/#usage
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${RADARR_CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/data
    network_mode: service:gluetun
    depends_on:
      - gluetun
  # https://docs.linuxserver.io/images/docker-prowlarr/#usage
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROWLARR_CONFIG_PATH}:/config
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - radarr
      - sonarr
  # https://docs.linuxserver.io/images/docker-bazarr/#usage
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BAZARR_CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/data
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - radarr
      - sonarr
  # lidarr:
  #   container_name: lidarr
  #   image: lscr.io/linuxserver/lidarr:latest
  #   restart: unless-stopped
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /docker/lidarr:/config
  #     - /data:/data
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los_Angeles
  #   ports:
  #     - 8686:8686

  # readarr:
  #   image: lscr.io/linuxserver/readarr:develop
  #   container_name: readarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los_Angeles
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /docker/readarr:/config
  #     - /data:/data
  #   ports:
  #     - 8787:8787
  #   restart: unless-stopped

  # nzbget:
  #   image: lscr.io/linuxserver/nzbget:latest
  #   container_name: nzbget
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los_Angeles
  #     - NZBGET_USER=user
  #     - NZBGET_PASS=password
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /docker/nzbget:/config
  #     - /data:/data
  #   restart: unless-stopped
  #   network_mode: service:gluetun
networks: {}
